name: Publish Package to npmjs
on:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: cd src && tsc
      - run: cp ./README.md ./src/README.md
      - run: cd src && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
